=== Aryan6001/candidate-data-transformer-system/src/main/resources/candidate-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",

  "type": "object",

  "required": [
    "candidateId",
    "fullName"
  ],

  "properties": {

    "candidateId": {
      "type": "string"
    },

    "fullName": {
      "type": "string"
    },

    "primaryEmail": {
      "type": [
        "string",
        "null"
      ]
    },

    "primaryPhone": {
      "type": [
        "string",
        "null"
      ]
    },

    "skills": {
      "type": "array"
    },

    "experience": {
      "type": "array"
    },

    "education": {
      "type": "array"
    },

    "overall_confidence": {
      "type": [
        "number",
        "null"
      ]
    },

    "provenance": {
      "type": [
        "array",
        "null"
      ]
    }

  }
}

=== Aryan6001/candidate-data-transformer-system/output/candidate.json
{
  "candidateId" : "1001",
  "fullName" : "John Smith",
  "primaryEmail" : "john.smith@gmail.com",
  "primaryPhone" : "+919876543210",
  "skills" : [ {
    "name" : "Kubernetes",
    "confidence" : 0.9,
    "sources" : [ "Resume" ]
  }, {
    "name" : "SQL",
    "confidence" : 0.9,
    "sources" : [ "Resume" ]
  }, {
    "name" : "Docker",
    "confidence" : 0.9,
    "sources" : [ "Resume" ]
  }, {
    "name" : "Spring",
    "confidence" : 0.9,
    "sources" : [ "Resume" ]
  }, {
    "name" : "Spring Boot",
    "confidence" : 0.9,
    "sources" : [ "Resume" ]
  }, {
    "name" : "Java",
    "confidence" : 0.9,
    "sources" : [ "Resume" ]
  } ],
  "experience" : [ ],
  "education" : [ ],
  "overall_confidence" : null,
  "provenance" : null
}
